### ISSUE TITLE
complete code

### ISSUE THREAD

**Issue by dewisaf25** [Asr419/RSTSF#2]
Hello. Can I get the complete code? I'm still confused about the code for generating FRST rules, the confusion matrix for RST and FRST, the accuracy of the grid search, and the discretisation. thank you
email : dewisaf251001@gmail.com

**Comment by Asr419** [comment]
If you would see in RST based stock market forecasting Jupiter notebook there is a Discretization.RST library of R.

**Comment by dewisaf25** [comment]
Thank you. Sorry for asking again, can i know the code for find the accuracy scores for each value of x? because in the code (Comparison with ML models.ipynb) there's no code for that. Thank you
![Screenshot_20230627_141817](https://github.com/Asr419/RSTSF/assets/116559738/d1decfdd-d6d6-4b85-acc1-27bb2a2fc781)

**Comment by Asr419** [comment]
This different values of X is only used in the rst+cn2 algorithm which is
in rst based stock marketing jupyter notebook the target was to empirically
find a value of X for this algorithm that would beat the ml models accuracy.
